version: '3.9'

services:
  app:
    build: 
      context: .
    env_file:
      - .env
    container_name: forge
    command: ['/app/docker/app.bash']
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres
    volumes:
      - ./bot:/bot
      - postgres_volume:/var/lib/postgressql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Forge
    ports:
      - 5432:5432


volumes:
  postgres_volume: