services:
  app:
    build: 
      context: .
    env_file:
      - .env
    container_name: forge
    command: ['/app/docker/app.sh']
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    ports:
      - 9000:8000
    depends_on:
      - db
    networks:
      - net

  db:
    image: postgres:16
    container_name: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Forge
    command: -p 5433
    expose:
      - 5435
    ports:
      - 5435:5433
    networks:
      - net


volumes:
  db:
    driver: local


networks:
  net: