"""add ondelet RESTRICT

Revision ID: 86f4cfc961b4
Revises: 91abb2ec6863
Create Date: 2024-05-17 20:38:12.710923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f4cfc961b4'
down_revision: Union[str, None] = '91abb2ec6863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dataset_user_id_fkey', 'dataset', type_='foreignkey')
    op.drop_constraint('dataset_type_dataset_id_fkey', 'dataset', type_='foreignkey')
    op.create_foreign_key(None, 'dataset', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'dataset', 'type_dataset', ['type_dataset_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint('dataset_order_dataset_id_fkey', 'dataset_order', type_='foreignkey')
    op.create_foreign_key(None, 'dataset_order', 'dataset', ['dataset_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(None, 'dataset_order', type_='foreignkey')
    op.create_foreign_key('dataset_order_dataset_id_fkey', 'dataset_order', 'dataset', ['dataset_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.create_foreign_key('dataset_type_dataset_id_fkey', 'dataset', 'type_dataset', ['type_dataset_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('dataset_user_id_fkey', 'dataset', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
