"""add columns

Revision ID: 4f4b8b1b6cde
Revises: 96ce4dd8cf7d
Create Date: 2024-05-16 17:25:06.071171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4b8b1b6cde'
down_revision: Union[str, None] = '96ce4dd8cf7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_dataset', sa.Column('first_frame', sa.String(length=100), nullable=False))
    op.add_column('company_dataset', sa.Column('second_frame', sa.String(length=100), nullable=False))
    op.add_column('user_dataset', sa.Column('first_frame', sa.String(length=100), nullable=False))
    op.add_column('user_dataset', sa.Column('second_frame', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_dataset', 'second_frame')
    op.drop_column('user_dataset', 'first_frame')
    op.drop_column('company_dataset', 'second_frame')
    op.drop_column('company_dataset', 'first_frame')
    # ### end Alembic commands ###
